apiVersion: v1
kind: Service
metadata:
  name: setel-payment
  namespace: setel
spec:
  selector:
    app: setel-payment
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: setel-payment
  namespace: setel
spec:
  selector:
    matchLabels:
      app: setel-payment
  template:
    metadata:
      labels:
        app: setel-payment
    spec:
      containers:
        - name: setel-payment
          image: setel-payment:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: mongodb://mongo:27017
            - name: REDIS_URL
              value: redis://redis:6379
